toastr feature/toastr container clone element
qeek-dev/react-qui pull request #33
Opened 2017-12-28 02:55 UTC by Chun-Lin

## DONE
* Use **cloneElement** to send props data to children
* Use **ReactCSSTransitionGroup** to implement animation feature

There are two ways to see the demos.
1. `yarn styleguide` to see the styles of toastrs
2. `yarn start` to see the demo page

2017-12-28 03:40 UTC, purepennons commented
@Chun-Lin 
有 warning ci 會擋掉

2017-12-29 07:31 UTC, purepennons requested changes

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/Toastr.js
> +    children: PropTypes.oneOfType([
children 可以是 array 吧？

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +    if (this.state.queue.length < 0) return
提到 const 之前，可以避免無意義多餘運算。

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +    duration: 5,
當初說統一成毫秒

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +    window.setTimeout(() => {
養成習慣，要把 return id 存起來，然後在 componentWillUnmount 的時候 clearTimeout，不然可能造成 memory leak。

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +  trigger = () => {
傳入 childProps，改成可以動態修改 children props

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +    position: PropTypes.string,
還缺六個方位的 class。

2017-12-29 07:31 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/index.js
> +export { default as Toastr } from './components/Toastr/Toastr';
名稱有要統一嗎？邏輯相關就元件名稱 (`<Toastr>`），Q 才能使用的 View 就 `<QToastr>` ?

所以：
- Toastr -> QToastr
- ToastrContainer -> Toastr

2017-12-29 07:32 UTC, purepennons commented
@Chun-Lin 

如果 styleguidist 無法修好的話，記得在 readme 上補上用法。

2017-12-29 08:11 UTC, purepennons requested changes

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/lib/components/Toastr/Toastr.md
> +  toastrContainer.info('Hello!!!', 5)
這個 info 是？

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/package.json
> +  "dependencies": {
沒用到的 dependencies 可以拔掉。

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/package.json
> +  "dependencies": {
可以的話，幫我試試看拔成 devDependencies ，看會不會壞掉，不然每個套件都太肥了。

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/Toastr.js
> +    this.getContainerStyle(this.props)
無意義程式碼，沒 value 去接他

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/Toastr.js
> +    const widthWithoutPadding = width - 48
48 要拉成有意義的變數再使用

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +        toastrStyle,
這是屬於 Toastr 的樣式設定，不應該是 Container 的 props。這是使用時，Toastr 要寫死的。記得一併把 propTypes 移除。

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +      let newItems = this.state.queue.slice(1)
`newItems ` 並沒有 reassign，請用 const

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/ToastrContainer.js
> +      let newItems = this.state.queue.slice(1)
而且這是用於下次變化的 state，在 setState 中的 prevState 設定才安全。

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/styles/animation.css
> +  opacity: 0.01;
為什麼要先設成 0.01?

2017-12-29 08:11 UTC, purepennons commented on packages/toastr/package.json
> +  "name": "react-qui-toastr",
名稱需要為 `@react-qui/toastr`

2018-01-02 04:27 UTC, Chun-Lin commented on packages/toastr/lib/components/Toastr/Toastr.md
> +  toastrContainer.info('Hello!!!', 5)
無意義的程式碼

2018-01-02 04:27 UTC, Chun-Lin commented on packages/toastr/src/react-component-node-modules/components/Toastr/styles/animation.css
> +  opacity: 0.01;
因為react animation add-on範例是opacity 0.01開始，其實設成0也是可以的，只是因為幾乎沒影響，所以我就沒改成0

2018-01-02 04:29 UTC, Chun-Lin commented on packages/toastr/package.json
> +  "dependencies": {
從Dependencies拔到devDependencies可以work

2018-01-02 04:29 UTC, Chun-Lin commented on packages/toastr/src/react-component-node-modules/index.js
> +export { default as Toastr } from './components/Toastr/Toastr';
ok, 我把名稱統一了，邏輯層統一叫做Toastr，有用到QNAP的style就叫做QToastr

2018-01-09 09:04 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/Toastr.js
> +    if (!this.id) return
this.timeID 才對

2018-01-09 09:04 UTC, purepennons commented on packages/toastr/src/react-component-node-modules/components/Toastr/styles/Toastr.scss
> +.view-page {
給他一個很高的 z-index，不然會被其他東西蓋過去。（甚至設定 opacity: 0.999 也行 XD...）

2018-01-09 09:09 UTC, purepennons commented
- 另外補上 stylegudist 的 markdown，我試過是可以的
```js
let toastr;
<div>
  <button onClick={evt => toastr.trigger({children: <span>No, changed!</span>})}>trigger</button>
  <Toastr
    position="top-right"
    duration={5000}
    ref={ref => toastr = ref}
  >
    <QToastr toastrStyle="qts">Default Message</QToastr>
  </Toastr>
</div>
```

- center 在某些情況下會偏移，還不確定原因 （不管是 top or bottom）
<img width="1312" alt="screen shot 2018-01-09 at 5 01 30 pm" src="https://user-images.githubusercontent.com/4588113/34712921-8573808e-f55f-11e7-9eff-f44f05e2fe34.png">

2018-01-16 07:30 UTC, purepennons approved these changes

2018-01-16 07:31 UTC, merged